// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Assignment_gRPC/calculator.proto

package calculator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TwoNumRequest struct {
	Num1                 int64    `protobuf:"varint,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2                 int64    `protobuf:"varint,2,opt,name=num2,proto3" json:"num2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TwoNumRequest) Reset()         { *m = TwoNumRequest{} }
func (m *TwoNumRequest) String() string { return proto.CompactTextString(m) }
func (*TwoNumRequest) ProtoMessage()    {}
func (*TwoNumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5203e23a174b8df, []int{0}
}

func (m *TwoNumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwoNumRequest.Unmarshal(m, b)
}
func (m *TwoNumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwoNumRequest.Marshal(b, m, deterministic)
}
func (m *TwoNumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwoNumRequest.Merge(m, src)
}
func (m *TwoNumRequest) XXX_Size() int {
	return xxx_messageInfo_TwoNumRequest.Size(m)
}
func (m *TwoNumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TwoNumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TwoNumRequest proto.InternalMessageInfo

func (m *TwoNumRequest) GetNum1() int64 {
	if m != nil {
		return m.Num1
	}
	return 0
}

func (m *TwoNumRequest) GetNum2() int64 {
	if m != nil {
		return m.Num2
	}
	return 0
}

type SumResponse struct {
	Sum                  int64    `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5203e23a174b8df, []int{1}
}

func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (m *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(m, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetSum() int64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

type NumRequest struct {
	Num                  int64    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumRequest) Reset()         { *m = NumRequest{} }
func (m *NumRequest) String() string { return proto.CompactTextString(m) }
func (*NumRequest) ProtoMessage()    {}
func (*NumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5203e23a174b8df, []int{2}
}

func (m *NumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumRequest.Unmarshal(m, b)
}
func (m *NumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumRequest.Marshal(b, m, deterministic)
}
func (m *NumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumRequest.Merge(m, src)
}
func (m *NumRequest) XXX_Size() int {
	return xxx_messageInfo_NumRequest.Size(m)
}
func (m *NumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NumRequest proto.InternalMessageInfo

func (m *NumRequest) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type AllPrimesResponse struct {
	Num                  int64    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllPrimesResponse) Reset()         { *m = AllPrimesResponse{} }
func (m *AllPrimesResponse) String() string { return proto.CompactTextString(m) }
func (*AllPrimesResponse) ProtoMessage()    {}
func (*AllPrimesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5203e23a174b8df, []int{3}
}

func (m *AllPrimesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllPrimesResponse.Unmarshal(m, b)
}
func (m *AllPrimesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllPrimesResponse.Marshal(b, m, deterministic)
}
func (m *AllPrimesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllPrimesResponse.Merge(m, src)
}
func (m *AllPrimesResponse) XXX_Size() int {
	return xxx_messageInfo_AllPrimesResponse.Size(m)
}
func (m *AllPrimesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllPrimesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllPrimesResponse proto.InternalMessageInfo

func (m *AllPrimesResponse) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type AverageResponse struct {
	Num                  int64    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AverageResponse) Reset()         { *m = AverageResponse{} }
func (m *AverageResponse) String() string { return proto.CompactTextString(m) }
func (*AverageResponse) ProtoMessage()    {}
func (*AverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5203e23a174b8df, []int{4}
}

func (m *AverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AverageResponse.Unmarshal(m, b)
}
func (m *AverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AverageResponse.Marshal(b, m, deterministic)
}
func (m *AverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AverageResponse.Merge(m, src)
}
func (m *AverageResponse) XXX_Size() int {
	return xxx_messageInfo_AverageResponse.Size(m)
}
func (m *AverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AverageResponse proto.InternalMessageInfo

func (m *AverageResponse) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type MaxNumResponse struct {
	Num                  int64    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxNumResponse) Reset()         { *m = MaxNumResponse{} }
func (m *MaxNumResponse) String() string { return proto.CompactTextString(m) }
func (*MaxNumResponse) ProtoMessage()    {}
func (*MaxNumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5203e23a174b8df, []int{5}
}

func (m *MaxNumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxNumResponse.Unmarshal(m, b)
}
func (m *MaxNumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxNumResponse.Marshal(b, m, deterministic)
}
func (m *MaxNumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxNumResponse.Merge(m, src)
}
func (m *MaxNumResponse) XXX_Size() int {
	return xxx_messageInfo_MaxNumResponse.Size(m)
}
func (m *MaxNumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxNumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MaxNumResponse proto.InternalMessageInfo

func (m *MaxNumResponse) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func init() {
	proto.RegisterType((*TwoNumRequest)(nil), "calculator.TwoNumRequest")
	proto.RegisterType((*SumResponse)(nil), "calculator.SumResponse")
	proto.RegisterType((*NumRequest)(nil), "calculator.NumRequest")
	proto.RegisterType((*AllPrimesResponse)(nil), "calculator.AllPrimesResponse")
	proto.RegisterType((*AverageResponse)(nil), "calculator.AverageResponse")
	proto.RegisterType((*MaxNumResponse)(nil), "calculator.MaxNumResponse")
}

func init() { proto.RegisterFile("Assignment_gRPC/calculator.proto", fileDescriptor_e5203e23a174b8df) }

var fileDescriptor_e5203e23a174b8df = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xdb, 0x55, 0x3c, 0x3c, 0xed, 0x36, 0x73, 0xd0, 0x39, 0x51, 0x47, 0x44, 0xd8, 0xa9,
	0x9b, 0xf5, 0xe0, 0x61, 0xa7, 0x5a, 0x10, 0x76, 0xb0, 0x8c, 0xce, 0x93, 0x17, 0x69, 0x67, 0x28,
	0x85, 0x26, 0xa9, 0x49, 0xa3, 0xfe, 0x4d, 0xfe, 0x95, 0xd2, 0x5a, 0xd6, 0x44, 0x99, 0xb7, 0xf0,
	0xbd, 0xef, 0xfd, 0x78, 0xdf, 0x47, 0x60, 0x12, 0x48, 0x99, 0x67, 0x8c, 0x12, 0x56, 0xbd, 0x64,
	0xf1, 0x2a, 0x9c, 0x6d, 0x92, 0x62, 0xa3, 0x8a, 0xa4, 0xe2, 0xc2, 0x2b, 0x05, 0xaf, 0x38, 0x82,
	0x4e, 0xc1, 0x77, 0xe0, 0x3e, 0x7d, 0xf0, 0x48, 0xd1, 0x98, 0xbc, 0x29, 0x22, 0x2b, 0x84, 0x60,
	0x8f, 0x29, 0x7a, 0x33, 0xb2, 0x27, 0xf6, 0xd4, 0x89, 0x9b, 0x77, 0xab, 0xf9, 0xa3, 0xde, 0x56,
	0xf3, 0xf1, 0x25, 0x1c, 0xac, 0xeb, 0x2d, 0x59, 0x72, 0x26, 0x09, 0x1a, 0x82, 0x23, 0x15, 0x6d,
	0xb7, 0xea, 0x27, 0xbe, 0x00, 0xd0, 0xb0, 0x43, 0x70, 0x58, 0x37, 0x67, 0x8a, 0xe2, 0x6b, 0x38,
	0x0a, 0x8a, 0x62, 0x25, 0x72, 0x4a, 0xa4, 0x8e, 0xf9, 0x65, 0xbb, 0x82, 0x41, 0xf0, 0x4e, 0x44,
	0x92, 0x91, 0x7f, 0x4c, 0x18, 0xfa, 0x8f, 0xc9, 0x67, 0x64, 0xde, 0x63, 0x7a, 0xfc, 0xaf, 0x1e,
	0x40, 0xb8, 0x0d, 0x8e, 0x16, 0xe0, 0xac, 0x15, 0x45, 0xa7, 0x9e, 0x56, 0x8f, 0xd1, 0xc4, 0xf8,
	0x44, 0x1f, 0x69, 0x59, 0xb1, 0x85, 0x96, 0x70, 0xd8, 0x1c, 0x1e, 0x29, 0x9a, 0x12, 0x21, 0xd1,
	0xb1, 0x6e, 0xd5, 0x10, 0xe7, 0xba, 0xfe, 0x27, 0x2d, 0xb6, 0xe6, 0x36, 0x5a, 0x42, 0x3f, 0xe4,
	0xb4, 0x54, 0x15, 0x69, 0x63, 0xee, 0x84, 0x9d, 0x19, 0x30, 0xb3, 0x13, 0x6c, 0x4d, 0x6b, 0x94,
	0xfb, 0x90, 0xb3, 0xd7, 0x9f, 0x26, 0x52, 0x22, 0x76, 0x92, 0xc6, 0xba, 0x6e, 0x16, 0x57, 0x83,
	0xe6, 0xf6, 0xfd, 0xe0, 0xd9, 0xf5, 0x66, 0x8b, 0xce, 0x95, 0xee, 0x37, 0x5f, 0xe7, 0xf6, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0x6b, 0xe8, 0x76, 0xf1, 0x5e, 0x02, 0x00, 0x00,
}
